server:
  port: 8079
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:mysql://localhost:3306/DB_TODO
    username: root
    password: password
  mvc:
    problemdetails:
      enabled: true
logging:
  level:
    root: debug
management:
  endpoint:
    health:
      show-details: always  # 加：health 端點才會顯示是哪個 indicator 掛了
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

services:
  user-service:
    uri: http://localhost:8078
  todo-service:
    uri: http://localhost:8079