apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/DB_TODO
  SPRING_DATASOURCE_USER: root
  SPRING_DATASOURCE_PASSWORD: password
