apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: password
