apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      role: backend-service
  template:
    metadata:
      labels:
        app: todo
        role: backend-service
    spec:
      containers:
        - name: user-service
          image: user-service:0.0.1
          resources:
            limits:
              cpu: "500m"
            reqests:
              cpu: "500m"
          ports:
            - containerPort: 8078
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      role: backend-service
  template:
    metadata:
      labels:
        app: todo
        role: backend-service
    spec:
      containers:
        - name: todo-service
          image: todo-service:0.0.1
          resources:
            limits:
              cpu: "500m"
            reqests:
              cpu: "500m"
          ports:
            - containerPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      role: database
  template:
    metadata:
      labels:
        app: todo
        role: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          reqests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306

