apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo
    role: backend-service
  ports:
  - port: 8078
    targetPort: 8078
    nodePort: 38078
  - port: 8079
    targetPort: 8079
    nodePort: 38079